title: Tobia Marcucci
email: marcucci AT ucsb DOT edu
description: Personal website of Tobia Marcucci.
github_username:  TobiaMarcucci

theme: minima

header_pages:
  - research.md
  - pubs.md
  - bio.md
  - cv.md
  - teaching.md
  - contacts.md
